name: 🐞 Bug Report
description: Tell us about something that's not working the way we (probably) intend.
labels: 'Type: Bug'
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please, make sure you check all checkboxes
      options:
        - label: Review the documentation: https://docs.sentry.io/
        - label: Search for existing issues: https://github.com/getsentry/sentry-javascript/issues
        - label: Use the latest release: https://github.com/getsentry/sentry-javascript/releases
        - label: Provide a link to the affected event from your Sentry account
  - type: dropdown
    id: type
    attributes:
      label: How do you use Sentry?
      options:
        - Sentry Saas (sentry.io)
        - Self-hosted/on-premise
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which SDK version?
      placeholder: ex. 1.5.2
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we see what you're seeing? Specific is terrific.
      placeholder: |-
        1. What
        2. you
        3. did.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: Logs? Screenshots? Yes, please.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
    validations:
      required: false
