name: 🐞 Bug Report
description: Tell us about something that's not working the way we (probably) intend.
labels: "Type: Bug"
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I reviewed the documentation https://docs.sentry.io/
          required: true
        - label: I checked for existing issues https://github.com/getsentry/sentry-javascript/issues
          required: true
        - label: I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases
          required: true
  - type: dropdown
    id: type
    attributes:
      label: How do you use Sentry?
      options:
        - Sentry Saas (sentry.io)
        - Self-hosted/on-premise
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: Which package are you using?
      options:
        - sentry/browser
        - sentry/nextjs
        - sentry/angular
        - sentry/ember
        - sentry/gatsby
        - sentry/integrations
        - sentry/node
        - sentry/react
        - sentry/serverless
        - sentry/vue
        - sentry/wasm
        - sentry/utils
        - raven-js
        - raven-node (raven for node)
    validations:
      required: true
  - type: input
    id: link-to-sentry
    attributes:
      label: Link to Sentry event
      description: Provide a link to the affected event from your Sentry account
      placeholder: https://sentry.io/organizations/sentry/issues/3006590523/?project=6183838
  - type: input
    id: version
    attributes:
      label: Version
      description: Which SDK version?
      placeholder: ex. 1.5.2
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we see what you're seeing? Specific is terrific.
      placeholder: |-
        1. What
        2. you
        3. did.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: Logs? Screenshots? Yes, please.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
    validations:
      required: false
