name: 🐞 Bug Report
description: Tell us about something that's not working the way we (probably) intend.
labels: "Type: Bug"
body:
  - type: dropdown
    id: type
    attributes:
      label: How do you use Sentry?
      options:
        - Sentry Saas (sentry.io)
        - Self-hosted/on-premise
    validations:
      required: true
